version: '3.8'

services:
  app:
    container_name: smart_thing_gateway
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8081:8081
      - 7779:7779 # logs
      - 7778:7778 # search
    network_mode: host
    volumes:
      - gateway-data:/app

volumes:
  gateway-data: {}